project: "project-zen"
flow_dir: "zen/flows/"
dockerfile: "configs/Dockerfile"
dockerignore: "configs/.dockerignore"
visualize_dir: "viz"
aws_profile: "default"
region_name: "ap-south-1"
ecr_registry_id: "<aws acount id>"
env:
  # NOTE: Required
  RESULTS_BUCKET: "value"
